#
# If not stated otherwise in this file or this component's Licenses.txt file the
# following copyright and licenses apply:
#
# Copyright 2016 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

BASE=$(shell pwd)/../
CID=$(BASE)/common/external/install

all:  externals

clean: init

cleanall: initall

setenv= \
	export PATH=$(CID)/bin:$(PATH) && \
	export LD_LIBRARY_PATH=$(CID)/lib && \
	export PKG_CONFIG_PATH=$(CID)/lib/pkgconfig:$(CID)/share/pkgconfig && \
	export PKG_CONFIG=$(CID)/bin/pkg-config &&  \
	export ACLOCAL_PATH=$(CID)/share/aclocal && \
	export ACLOCAL="aclocal -I $ACLOCAL_PATH"

initall: init
	rm -rf external
   
init:
	rm -f *.o && rm -f *.gcov && rm -f *.gcno && rm -f *.gcda
	rm -f *.o && rm -f *.lo && rm -f .libs/*
	rm -f .common

externals: external \
           external/.pkgconfig \
           external/.libffi \
           external/.libpcre \
           external/.zlib \
           external/.glib2.0 \
           external/.pthread-stubs \
           external/.xproto \
           external/.xau \
           external/.bison \
           external/.expat \
           external/.gettext-tools \
           external/.flex \
           external/.intltool \
           external/.proto \
           external/.macros \
           external/.xkbconfig \
           external/.libxcd \
           external/.libxkbcommon \
           external/.wayland \
           external/.gstreamer \
           external/.gst-plugins-base \
           external/.mesa
	rm -f $(CID)/share/config.site

external:
	mkdir -p external

external/.pkgconfig:	
	$(call setenv) && \
	cd external && \
	git clone git://anongit.freedesktop.org/pkg-config && \
	cd pkg-config && \
	git checkout pkg-config-0.29 && \
	patch -p1 < ../../../patches/pkg-config/fix-m4-copy-error.patch && \
	./autogen.sh --prefix $(CID) --no-configure && \
	./configure --prefix $(CID) --with-internal-glib && \
	patch -p1 < ../../../patches/pkg-config/gdate-fix-build-error.patch && \
	make && make install && \
	cd .. && \
	touch .pkgconfig

external/.libffi:
	$(call setenv) && \
	cd external && \
	mkdir libffi && \
	cd libffi && \
	wget http://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz && \
	tar xzvf libffi-3.2.1.tar.gz && \
	cd libffi-3.2.1 && \
	./configure --prefix $(CID) && \
	make && make install && \
	cd ../.. && \
	touch .libffi

external/.libpcre:
	$(call setenv) && \
	cd external && \
	mkdir libpcre && \
	cd libpcre && \
	wget https://sourceforge.net/projects/pcre/files/pcre/8.39/pcre-8.39.tar.bz2 && \
	tar xjvf pcre-8.39.tar.bz2 && \
	cd pcre-8.39 && \
	./configure --prefix $(CID) --enable-newline-is-lf --enable-rebuild-chartables --enable-utf --enable-unicode-properties --with-link-size=2 --with-match-limit=10000000 && \
	make && make install && \
	cd ../.. && \
	touch .libpcre	

external/.zlib:
	$(call setenv) && \
	cd external && \
	mkdir zlib && \
	cd zlib && \
	wget http://www.zlib.net/zlib-1.2.13.tar.xz && \
	tar xf zlib-1.2.13.tar.xz && \
	cd zlib-1.2.13/ && \
	./configure --prefix $(CID) && \
	make && make install && \
	cd ../.. && \
	touch .zlib

external/.glib2.0:
	$(call setenv) && \
	cd external && \
	mkdir glib2.0 && \
	cd glib2.0 && \
	wget http://ftp.gnome.org/pub/gnome/sources/glib/2.58/glib-2.58.2.tar.xz && \
	tar xf glib-2.58.2.tar.xz && \
	cd glib-2.58.2/ && \
	./autogen.sh --prefix $(CID) --enable-libmount=no && \
	make && make install && \
	cd ../.. && \
	touch .glib2.0

external/.pthread-stubs:
	$(call setenv) && \
	cd external && \
	mkdir pthread-stubs && \
	cd pthread-stubs && \
	wget https://gitlab.freedesktop.org/xorg/lib/pthread-stubs/-/archive/0.3/pthread-stubs-0.3.tar.gz && \
	tar xzvf pthread-stubs-0.3.tar.gz && \
	cd pthread-stubs-0.3 && \
	./autogen.sh --prefix $(CID) && \
	make && make install && \
	cd ../.. && \
	touch .pthread-stubs

external/.xproto:
	$(call setenv) && \
	cd external && \
	mkdir xproto && \
	cd xproto && \
	wget http://www.x.org/archive/individual/proto/xproto-7.0.29.tar.bz2 && \
	tar xjvf xproto-7.0.29.tar.bz2 && \
	cd xproto-7.0.29/ && \
	./configure --prefix $(CID) && \
	make && make install && \
	cd ../.. && \
	touch .xproto

external/.xau:
	$(call setenv) && \
	cd external && \
	mkdir xau && \
	cd xau && \
	wget http://www.x.org/pub/individual/lib/libXau-1.0.8.tar.bz2 && \
	tar xjvf libXau-1.0.8.tar.bz2 && \
	cd libXau-1.0.8 && \
	./configure --prefix $(CID) && \
	make && make install && \
	cd ../.. && \
	touch .xau	

external/.bison:
	$(call setenv) && \
	cd external && \
	mkdir bison && \
	cd bison && \
	wget http://ftp.gnu.org/gnu/bison/bison-3.1.tar.xz && \
	tar xf bison-3.1.tar.xz && \
	cd bison-3.1/ && \
	./configure --prefix $(CID) && \
	make && make install && \
	cd ../.. && \
	touch .bison	

external/.expat:
	$(call setenv) && \
	cd external && \
	mkdir expat && \
	cd expat && \
	wget https://sourceforge.net/projects/expat/files/expat/2.5.0/expat-2.5.0.tar.bz2 && \
	tar xjvf expat-2.5.0.tar.bz2 && \
	cd expat-2.5.0/ && \
	./configure --prefix $(CID) && \
	make && make install && \
	cd ../.. && \
	touch .expat	

external/.gettext-tools:
	$(call setenv) && \
	cd external && \
	mkdir gettext-tools && \
	cd gettext-tools && \
	wget http://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.5.1.tar.gz && \
	tar xzvf gettext-0.19.5.1.tar.gz && \
	cd gettext-0.19.5.1/ && \
	./configure --prefix $(CID) --without-lispdir --disable-csharp --disable-libasprintf --disable-java --disable-native-java --disable-openmp --disable-acl --with-included-glib --without-emacs --without-cvs --without-git --with-included-libxml --with-included-libcroco --with-included-libunistring && \
	make && make install && \
	cd ../.. && \
	touch .gettext-tools	

external/.flex:
	$(call setenv) && \
	cd external && \
	mkdir flex && \
	cd flex && \
	wget http://github.com/westes/flex/releases/download/v2.6.3/flex-2.6.3.tar.gz && \
	tar xzvf flex-2.6.3.tar.gz && \
	cd flex-2.6.3/ && \
	./autogen.sh --prefix $(CID) && \
	./configure --prefix $(CID) && make && make install && \
	cd ../.. && \
	touch .flex	

external/.intltool:
	$(call setenv) && \
	cd external && \
	mkdir intltool && \
	cd intltool && \
	wget https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/intltool/0.51.0-2/intltool_0.51.0.orig.tar.gz && \
	tar xzvf intltool_0.51.0.orig.tar.gz && \
	cd intltool-0.51.0 && \
	./configure --prefix $(CID) && \
	make && make install && \
	cd ../.. && \
	touch .intltool

external/.proto:	
	$(call setenv) && \
	cd external && \
	git clone git://anongit.freedesktop.org/xcb/proto && \
	cd proto && \
	./autogen.sh --prefix $(CID) && \
	make && make install && \
	cd .. && \
	touch .proto

external/.macros:
	$(call setenv) && \
	cd external && \
	git clone git://anongit.freedesktop.org/xorg/util/macros && \
	cd macros && \
	./autogen.sh --prefix $(CID) && \
	make && make install && \
	cd .. && \
	touch .macros

external/.xkbconfig:
	$(call setenv) && \
	cd external && \
	mkdir xkbconfig && \
	cd xkbconfig && \
	wget http://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.18.tar.bz2 && \
	tar xjvf xkeyboard-config-2.18.tar.bz2 && \
	cd xkeyboard-config-2.18 && \
	./autogen.sh --prefix $(CID) --disable-runtime-deps && \
	make && make install && \
	cd ../.. && \
	touch .xkbconfig

external/.libxcd:
	$(call setenv) && \
	cd external && \
	git clone git://anongit.freedesktop.org/xcb/libxcb && \
	cd libxcb && \
	./autogen.sh --prefix $(CID) && \
	make && make install && \
	cd .. && \
	touch .libxcd
	
external/.libxkbcommon:
	$(call setenv) && \
	cd external && \
	git clone https://github.com/xkbcommon/libxkbcommon.git && \
	cd libxkbcommon && \
	git checkout 73794e1e547704d7ba9242a8f7873e17631faecb && \
	./autogen.sh --prefix $(CID) && \
	make && make install && \
	cd .. && \
	touch .libxkbcommon

external/.wayland:
	$(call setenv) && \
	cd external && \
	mkdir wayland && \
	cd wayland && \
	wget http://wayland.freedesktop.org/releases/wayland-1.6.0.tar.xz && \
	tar xf wayland-1.6.0.tar.xz && \
	cd wayland-1.6.0 && \
	./configure --prefix $(CID) --with-expat=$(CID) --disable-documentation && \
	make && make install && \
	cd ../.. && \
	touch .wayland

external/.gstreamer:
	$(call setenv) && \
	cd external && \
	mkdir gstreamer1.0 && \
	cd gstreamer1.0 && \
	wget https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.10.4.tar.xz && \
	tar xf gstreamer-1.10.4.tar.xz && \
	cd gstreamer-1.10.4 && \
	./configure --prefix $(CID) && \
	make && make install && \
	cd ../.. && \
	touch .gstreamer

external/.gst-plugins-base:
	$(call setenv) && \
	cd external && \
	mkdir gst-plugins-base && \
	cd gst-plugins-base && \
	wget https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.10.4.tar.xz && \
	tar xf gst-plugins-base-1.10.4.tar.xz && \
	cd gst-plugins-base-1.10.4 && \
	patch -p1 < ../../../../patches/gst-plugins-base/fix-stray-char.patch && \
	./configure --prefix $(CID) && \
	make && make install && \
	cd ../.. && \
	touch .gst-plugins-base

external/.mesa:
	$(call setenv) && \
	cd external && \
	mkdir mesa && \
	cd mesa && \
	wget https://gitlab.freedesktop.org/mesa/mesa/-/archive/mesa-19.2.4/mesa-mesa-19.2.4.tar.gz && \
	tar xzvf mesa-mesa-19.2.4.tar.gz && \
	wget https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-2.4.100/drm-libdrm-2.4.100.tar.gz && \
	tar xzvf drm-libdrm-2.4.100.tar.gz && \
	cd .. && \
	touch .mesa

