#
# If not stated otherwise in this file or this component's Licenses.txt file the
# following copyright and licenses apply:
#
# Copyright 2016 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

BASE=$(shell pwd)/../
CID=$(BASE)/common/external/install
WID=$(BASE)/brcm/external/install

XDGOPT ?= xdgv4

all:  externals \
      site \
      westeros-protocols \
      westeros-simpleshell \
      westeros-simplebuffer \
      westeros-soc \
      westeros-core \
      westeros-essos \
      westeros-render-nexus \
      westeros-soc-sink \
      unit-test

clean: init

cleanall: initall

setenv= \
	export PATH=$(CID)/bin:$(WID)/bin:$(PATH) && \
	export LD_LIBRARY_PATH=$(CID)/lib:$(WID)/lib && \
	export PKG_CONFIG_PATH=$(CID)/lib/pkgconfig:$(CID)/share/pkgconfig && \
	export PKG_CONFIG=$(CID)/bin/pkg-config &&  \
	export ACLOCAL_PATH=$(WID)/share/aclocal && \
	export ACLOCAL="aclocal -I $ACLOCAL_PATH"

initall: init
	rm -rf external
   
init:
	cd protocol && rm -f *.h && rm -f *.c && rm -f *.o && rm -f *.lo && rm -f *.gcno
	cd protocol/version4 && rm -f *.h && rm -f *.c && rm -f *.o && rm -f *.lo && rm -f *.gcno
	cd protocol/version5 && rm -f *.h && rm -f *.c && rm -f *.o && rm -f *.lo && rm -f *.gcno
	cd simplebuffer/protocol && rm -f *.h && rm -f *.c && rm -f *.gcno
	cd simplebuffer && rm -f *.o && rm -f *.lo && rm -f *.gcno && rm -rf .libs/*
	cd simpleshell/protocol && rm -f *.h && rm -f *.c && rm -f *.gcno
	cd simpleshell && rm -f *.o && rm -f *.lo && rm -f *.gcno && rm -rf .libs/*
	cd essos && rm -f *.o && rm -f *.lo && rm -f *.gcno && rm -f && rm -f *.gcov
	cd brcm && rm -f *.o && rm -f *.lo && rm -f *.gcno && rm -f && rm -f *.gcov
	cd brcm/westeros-render-nexus && rm -f *.o && rm -f *.lo && rm -f *.gcno && rm -f && rm -f *.gcov
	cd brcm/westeros-sink && rm -f *.o && rm -f *.lo && rm -f *.gcno && rm -f && rm -f *.gcov
	cd ../brcm-em && rm -f *.o && rm -f *.gcov && rm -f *.gcno && rm -f *.gcda
	rm -f *.o && rm -f *.gcov && rm -f *.gcno && rm -f *.gcda
	rm -f *.o && rm -f *.lo && rm -f .libs/*
	rm -f .simplebuffer
	rm -f .simpleshell
	rm -f .brcm-em
	rm -f external/install/include/vpc*.h	
	
externals: external \
           external/.brcm-refsw
	rm -f $(WID)/share/config.site

external:
	mkdir -p external
	mkdir -p external/install
	
external/.brcm-refsw:
	cd external && \
	mkdir brcm-refsw && \
	cd brcm-refsw && \
	wget https://nexus.teamccp.com/nexus/service/local/repositories/broadcom/content/components/sdk/refsw/17_3/refsw_release_unified_20170922/2.1/refsw_release_unified_20170922-2.1.tgz && \
	mkdir temp && \
	cd temp && \
	tar xzvf ../refsw_release_unified_20170922-2.1.tgz && \
	cd .. && \
	mkdir include && \
	cp temp/magnum/basemodules/chp/include/common/bchp.h include && \
	cp temp/magnum/basemodules/chp/include/74295/rdb/a0/bchp_common.h include && \
	cp temp/magnum/basemodules/chp/include/common/bchp_ver_types.h include && \
	cp temp/magnum/basemodules/dbg/bdbg.h include && \
	cp temp/magnum/basemodules/dbg/bdbg_app.h include && \
	cp temp/magnum/basemodules/dbg/bdbg_priv.h include && \
	cp temp/magnum/basemodules/err/berr.h include && \
	cp temp/magnum/basemodules/kni/generic/bkni.h include && \
	cp temp/magnum/basemodules/kni/generic/bkni_multi.h include && \
	cp temp/magnum/commonutils/lst/blst_queue.h include && \
	cp temp/magnum/commonutils/lst/blst_slist.h include && \
	cp temp/magnum/portinginterface/grc/include/bm2mc_packet.h include && \
	cp temp/BSEAV/lib/media/bmedia_types.h include && \
	cp temp/magnum/basemodules/reg/breg_mem.h include && \
	cp temp/magnum/basemodules/reg/breg_mem_opt.h include && \
	cp temp/magnum/basemodules/reg/breg_mem_priv.h include && \
	cp temp/magnum/basemodules/reg/breg_tracelog.h include && \
	cp temp/magnum/basemodules/std/types/linuxuser/bstd_defs.h include && \
	cp temp/magnum/basemodules/std/bstd.h include && \
	cp temp/magnum/basemodules/std/bstd_file.h include && \
	cp temp/nexus/base/include/linuxuser/config/bstd_cfg.h include && \
	cp temp/BSEAV/lib/gpu/vc5/platform/nexus/default_nexus.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_amplifier.h include && \
	cp temp/nexus/modules/audio/include/ape_raaga/nexus_audio_init.h include && \
	cp temp/nexus/modules/audio/include/nexus_audio.h include && \
	cp temp/nexus/modules/audio/include/nexus_audio_dac.h include && \
	cp temp/nexus/modules/audio/include/nexus_audio_decoder_types.h include && \
	cp temp/nexus/modules/audio/include/nexus_audio_dsp.h include && \
	cp temp/nexus/modules/audio/include/nexus_audio_dummy_output.h include && \
	cp temp/nexus/modules/audio/include/nexus_audio_mixer.h include && \
	cp temp/nexus/modules/audio/include/nexus_audio_output.h include && \
	cp temp/nexus/modules/audio/include/nexus_audio_processing_types.h include && \
	cp temp/nexus/modules/core/include/nexus_audio_types.h include && \
	cp temp/nexus/base/include/public/nexus_base_os.h include && \
	cp temp/nexus/base/include/public/nexus_base_types.h include && \
	cp temp/nexus/base/include/public/nexus_base_types_client.h include && \
	cp temp/nexus/modules/cec/include/nexus_cec.h include && \
	cp temp/nexus/modules/display/include/nexus_ccir656_output.h include && \
	cp temp/nexus/modules/display/include/nexus_component_output.h include && \
	cp temp/nexus/modules/display/include/nexus_composite_output.h include && \
	cp temp/nexus/modules/core/include/nexus_core_compat.h include && \
	cp temp/nexus/modules/core/include/nexus_core_file_init.h include && \
	cp temp/nexus/modules/core/include/nexus_core_priv.h include && \
	cp temp/nexus/modules/core/include/nexus_core_utils.h include && \
	cp temp/nexus/modules/display/include/nexus_display.h include && \
	cp temp/nexus/modules/display/include/nexus_display_custom.h include && \
	cp temp/nexus/modules/display/include/nexus_display_init.h include && \
	cp temp/nexus/modules/display/include/nexus_display_types.h include && \
	cp temp/nexus/modules/display/include/nexus_display_utils.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_analog.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_card.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_dvb_c2.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_dvb_t2.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_dvbt.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_isdbt.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_ofdm.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_ofdm_types.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_oob.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_qam.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_satellite.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_t2_types.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_vsb.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_frontend_upstream.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_ifd.h include && \
	cp temp/nexus/modules/gpio/include/nexus_gpio.h include && \
	cp temp/nexus/modules/graphics2d/include/nexus_graphics2d.h include && \
	cp temp/nexus/modules/graphics2d/include/nexus_graphics2d_init.h include && \
	cp temp/nexus/modules/display/include/nexus_hddvi_input.h include && \
	cp temp/nexus/modules/hdmi_input/include/nexus_hdmi_input.h include && \
	cp temp/nexus/modules/hdmi_input/include/nexus_hdmi_input_hdcp_types.h include && \
	cp temp/nexus/modules/hdmi_output/include/nexus_hdmi_output.h include && \
	cp temp/nexus/modules/hdmi_output/include/nexus_hdmi_output_control.h include && \
	cp temp/nexus/modules/hdmi_output/include/nexus_hdmi_output_extra.h include && \
	cp temp/nexus/modules/hdmi_output/include/nexus_hdmi_output_hdcp.h include && \
	cp temp/nexus/modules/core/include/nexus_hdmi_types.h include && \
	cp temp/nexus/modules/i2c/include/nexus_i2c.h include && \
	cp temp/nexus/modules/audio/include/nexus_i2s_output.h include && \
	cp temp/nexus/modules/transport/include/nexus_input_band.h include && \
	cp temp/nexus/modules/core/include/nexus_memory.h include && \
	cp temp/nexus/modules/display/include/nexus_picture_quality_types.h include && \
	cp temp/nexus/modules/transport/include/nexus_pid_channel.h include && \
	cp temp/nexus/platforms/common/include/nexus_platform_client.h include && \
	cp temp/nexus/platforms/common/include/nexus_platform.h include && \
	cp temp/nexus/platforms/common/include/nexus_platform_generic_features_priv.h include && \
	cp temp/nexus/platforms/common/include/nexus_platform_common.h include && \
	cp temp/nexus/platforms/common/include/nexus_platform_common_version.h include && \
	cp temp/nexus/platforms/97250/include/nexus_platform_features.h include && \
	cp temp/nexus/platforms/common/include/nexus_platform_init.h include && \
	cp temp/nexus/platforms/common/include/nexus_platform_memconfig.h include && \
	cp temp/nexus/platforms/common/include/nexus_platform_server.h include && \
	cp temp/nexus/platforms/common/include/nexus_platform_standby.h include && \
	cp temp/nexus/platforms/97250/include/nexus_platform_version.h include && \
	cp temp/nexus/modules/pwm/include/nexus_pwm.h include && \
	cp temp/nexus/modules/pwm/include/nexus_pwm_init.h include && \
	cp temp/nexus/modules/transport/include/nexus_rave.h include && \
	cp temp/nexus/modules/sage/include/nexus_sage_init.h include && \
	cp temp/nexus/modules/sage/include/nexus_sage_types.h include && \
	cp temp/nexus/modules/security/include/nexus_security_init.h include && \
	cp temp/nexus/modules/security/include/nexus_security_datatypes.h include && \
	cp temp/nexus/modules/core/include/nexus_security_types.h include && \
	cp temp/nexus/modules/simple_decoder/include/nexus_simple_decoder_types.h include && \
	cp temp/nexus/modules/simple_decoder/include/nexus_simple_stc_channel.h include && \
	cp temp/nexus/modules/simple_decoder/include/nexus_simple_video_decoder.h include && \
	cp temp/nexus/modules/smartcard/include/nexus_smartcard.h include && \
	cp temp/nexus/modules/smartcard/include/nexus_smartcard_init.h include && \
	cp temp/nexus/modules/audio/include/nexus_spdif_output.h include && \
	cp temp/nexus/modules/hdmi_input/include/nexus_spdif_types.h include && \
	cp temp/nexus/modules/spi/include/nexus_spi.h include && \
	cp temp/nexus/modules/transport/include/nexus_stc_channel.h include && \
	cp temp/nexus/modules/transport/include/nexus_stc_channel_types.h include && \
	cp temp/nexus/modules/surface/include/nexus_striped_surface.h include && \
	cp temp/nexus/modules/surface_compositor/include/nexus_surface_client.h include && \
	cp temp/nexus/modules/surface_compositor/include/nexus_surface_compositor_types.h include && \
	cp temp/nexus/modules/surface/include/nexus_surface.h include && \
	cp temp/nexus/modules/surface/include/nexus_surface_init.h include && \
	cp temp/nexus/modules/surface/include/nexus_surface_types.h include && \
	cp temp/nexus/modules/display/include/nexus_svideo_output.h include && \
	cp temp/nexus/modules/transport/include/nexus_timebase.h include && \
	cp temp/nexus/modules/transport/include/nexus_transport_capabilities.h include && \
	cp temp/nexus/modules/transport/include/nexus_transport_init.h include && \
	cp temp/nexus/modules/transport/include/nexus_transport_wakeup.h include && \
	cp temp/nexus/modules/core/include/nexus_types.h include && \
	cp temp/nexus/modules/frontend/common/include/nexus_tuner.h include && \
	cp temp/nexus/modules/display/include/nexus_vbi.h include && \
	cp temp/nexus/modules/video_decoder/include/nexus_video_decoder.h include && \
	cp temp/nexus/modules/video_decoder/include/nexus_video_decoder_extra.h include && \
	cp temp/nexus/modules/video_decoder/include/nexus_video_decoder_init.h include && \
	cp temp/nexus/modules/video_decoder/include/nexus_video_decoder_types.h include && \
	cp temp/nexus/modules/video_decoder/include/nexus_video_decoder_userdata.h include && \
	cp temp/nexus/modules/video_encoder/include/nexus_video_encoder_init.h include && \
	cp temp/nexus/modules/video_encoder/include/nexus_video_encoder_types.h include && \
	cp temp/nexus/modules/display/include/nexus_video_image_input.h include && \
	cp temp/nexus/modules/core/include/nexus_video_types.h include && \
	cp temp/nexus/nxclient/include/nxclient.h include && \
	cp temp/nexus/nxclient/include/nxclient_global.h include && \
	cp temp/nexus/nxclient/include/nxclient_standby.h include && \
	rm refsw_release_unified_20170922-2.1.tgz && \
	rm -rf temp && \
	cd .. && \
	touch .brcm-refsw

site:
	mkdir -p $(WID)/share && \
	cp ../brcm-em/config.site $(WID)/share

westeros-protocols: xdg-shell-v4 xdg-shell-v5 simpleshell simplebuffer

xdg-shell-v4: protocol/version4/xdg-shell-server-protocol.h \
              protocol/version4/xdg-shell-protocol.c

protocol/version4/xdg-shell-server-protocol.h: protocol/version4/xdg-shell.xml
	export SCANNER_TOOL=${CID}/bin/wayland-scanner && \
	make -C protocol

protocol/version4/xdg-shell-protocol.c: protocol/version4/xdg-shell.xml
	export SCANNER_TOOL=${CID}/bin/wayland-scanner && \
	make -C protocol

xdg-shell-v5: protocol/version5/xdg-shell-server-protocol.h \
              protocol/version5/xdg-shell-protocol.c

protocol/version5/xdg-shell-server-protocol.h: protocol/version5/xdg-shell.xml
	export SCANNER_TOOL=${CID}/bin/wayland-scanner && \
	make -C protocol

protocol/version5/xdg-shell-protocol.c: protocol/version5/xdg-shell.xml
	export SCANNER_TOOL=${CID}/bin/wayland-scanner && \
	make -C protocol
	
simpleshell: simpleshell/protocol/simpleshell-client-protocol.h \
             simpleshell/protocol/simpleshell-server-protocol.h \
             simpleshell/protocol/simpleshell-protocol.c

simpleshell/protocol/simpleshell-client-protocol.h:
	export SCANNER_TOOL=${CID}/bin/wayland-scanner && \
	make -C simpleshell/protocol

simpleshell/protocol/simpleshell-server-protocol.h:
	export SCANNER_TOOL=${CID}/bin/wayland-scanner && \
	make -C simpleshell/protocol

simpleshell/protocol/simpleshell-protocol.c:
	export SCANNER_TOOL=${CID}/bin/wayland-scanner && \
	make -C simpleshell/protocol

westeros-simpleshell: .simpleshell

.simpleshell:
	$(call setenv) && \
	cd simpleshell && \
	mkdir -p m4 && \
	aclocal -I cfg && \
	libtoolize --automake && \
	autoheader && \
	automake --foreign --add-missing && \
	rm -f configure && \
	autoconf && \
	./configure --prefix $(WID) && \
	make && make install && \
	cd .. && \
	touch .simpleshell

simplebuffer: simplebuffer/protocol/simplebuffer-client-protocol.h \
             simplebuffer/protocol/simplebuffer-server-protocol.h \
             simplebuffer/protocol/simplebuffer-protocol.c

simplebuffer/protocol/simplebuffer-client-protocol.h:
	export SCANNER_TOOL=${CID}/bin/wayland-scanner && \
	make -C simplebuffer/protocol

simplebuffer/protocol/simplebuffer-server-protocol.h:
	export SCANNER_TOOL=${CID}/bin/wayland-scanner && \
	make -C simplebuffer/protocol

simplebuffer/protocol/simplebuffer-protocol.c:
	export SCANNER_TOOL=${CID}/bin/wayland-scanner && \
	make -C simplebuffer/protocol

westeros-simplebuffer: .simplebuffer

.simplebuffer:
	$(call setenv) && \
	cd simplebuffer && \
	mkdir -p m4 && \
	aclocal -I cfg && \
	libtoolize --automake && \
	autoheader && \
	automake --foreign --add-missing && \
	rm -f configure && \
	autoconf && \
	./configure --prefix $(WID) && \
	make && make install && \
	cd .. && \
	touch .simplebuffer

.brcm-em:
	mkdir -p $(WID)/usr/include && \
	cp ../brcm-em/wayland-egl.pc $(CID)/share/pkgconfig && \
	cp ../brcm-em/include/platform_app.inc $(WID)/usr/include && \
	cp ../brcm-em/include/* $(WID)/include -r && \
	cp ./external/brcm-refsw/include/* $(WID)/include -r && \
	cd ../brcm-em/em && \
	$(call setenv) && \
	export SCANNER_TOOL=$(CID)/bin/wayland-scanner && \
	make -C protocol && \
	mkdir -p m4 && \
	aclocal -I cfg && \
	libtoolize --automake && \
	autoheader && \
	automake --foreign --add-missing && \
	rm -f configure && \
	autoconf --include=$(WID)/include && \
	./configure --prefix $(WID) && \
	make && make install && \
	cd $(WID)/lib && \
	rm -f libnxclient.so && ln -s libwesteros-ut-em.so.0.0.0 libnxclient.so && \
	rm -f libnexus.so && ln -s libwesteros-ut-em.so.0.0.0 libnexus.so && \
	rm -f libwayland-egl.so.0 && ln -s libwesteros-ut-em.so.0.0.0 libwayland-egl.so.0 && \
	rm -f libwayland-egl.so && ln -s libwesteros-ut-em.so.0.0.0 libwayland-egl.so && \
	rm -f libEGL.so && ln -s libwesteros-ut-em.so.0.0.0 libEGL.so && \
	rm -f libGLESv2.so && ln -s libwesteros-ut-em.so.0.0.0 libGLESv2.so && \
	cd ../../.. && \
	touch .brcm-em

westeros-soc: .brcm-em
	$(call setenv) && \
	cd brcm && \
	mkdir -p m4 && \
	aclocal -I cfg && \
	libtoolize --automake && \
	autoheader && \
	automake --foreign --add-missing && \
	rm -f configure && \
	autoconf --include=$(WID)/include && \
	./configure --prefix $(WID) && \
	export PKG_CONFIG_SYSROOT_DIR=$(WID) && \
	make && make install

westeros-core:
	$(call setenv) && \
	mkdir -p m4 && \
	aclocal -I cfg && \
	libtoolize --automake && \
	autoheader && \
	automake --foreign --add-missing && \
	rm -f configure && \
	autoconf && \
	./configure --prefix $(WID) --enable-${XDGOPT} --enable-rendergl --enable-app --enable-test --enable-embedded=yes --enable-sbprotocol=yes --enable-essos=no && \
	make && make install

westeros-essos:
	$(call setenv) && \
	cd essos && \
	aclocal -I cfg && \
	libtoolize --automake && \
	autoheader && \
	automake --foreign --add-missing && \
	rm -f configure && \
	autoconf && \
	./configure --prefix $(WID) && \
	make && make install

westeros-render-nexus:
	$(call setenv) && \
	cd brcm/westeros-render-nexus && \
	aclocal -I cfg && \
	libtoolize --automake && \
	autoheader && \
	automake --foreign --add-missing && \
	rm -f configure && \
	autoconf --include=$(WID)/include && \
	./configure --prefix $(WID) && \
	make && make install

westeros-soc-sink:
	$(call setenv) && \
	cp westeros-sink/westeros-sink.c brcm/westeros-sink/westeros-sink.c && \
	cp westeros-sink/westeros-sink.h brcm/westeros-sink/westeros-sink.h && \
	cd brcm/westeros-sink && \
	aclocal -I cfg && \
	libtoolize --automake && \
	autoheader && \
	automake --foreign --add-missing && \
	rm -f configure && \
	autoconf --include=$(WID)/include && \
	./configure --prefix $(WID) --enable-gstreamer1 && \
	export PKG_CONFIG_SYSROOT_DIR=$(WID) && \
	make && make install

unit-test:
	cd ../brcm-em && \
	$(call setenv) && \
	mkdir -p m4 && \
	aclocal -I cfg && \
	libtoolize --automake && \
	autoheader && \
	automake --foreign --add-missing && \
	rm -f configure && \
	autoconf --include=$(WID)/include && \
	./configure --prefix $(WID) && \
	make && make install


