#
# If not stated otherwise in this file or this component's Licenses.txt file the
# following copyright and licenses apply:
#
# Copyright 2018 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

WID=$(shell pwd)/external/install

all:  parse-coverage test-brcm

clean:
	rm -f *.o && rm -f *.gcov && rm -f *.gcno && rm -f *.gcda && \
	rm -f parse-coverage && \
	cd brcm && \
	make -f Makefile.brcm clean && \
	cp ../Makefile.brcm . && \
	cd ..

cleanall: initall

setenv= \
	export PKG_CONFIG_PATH=$(WID)/lib/pkgconfig:$(WID)/share/pkgconfig && \
	export ACLOCAL_PATH=$(WID)/share/aclocal && \
	export ACLOCAL="aclocal -I $ACLOCAL_PATH"

initall: init
	rm -rf brcm
   
init:
	rm -f .brcm

parse-coverage:
	g++ parse-coverage.cpp -O2 -o parse-coverage

test-brcm: .brcm
	cd brcm && \
	make -f Makefile.brcm && \
	cd ..

.brcm:
	git clone https://code.rdkcentral.com/r/a/components/opensource/westeros brcm && \
	cd brcm && \
	cp ../Makefile.brcm . && \
	cd .. && \
	touch .brcm

