#
# If not stated otherwise in this file or this component's Licenses.txt file the
# following copyright and licenses apply:
#
# Copyright 2018 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

all:  parse-coverage test-common test-brcm test-drm

clean:
	rm -f *.o && rm -f *.gcov && rm -f *.gcno && rm -f *.gcda && \
	rm -f parse-coverage && \
	cd common && \
	make -f Makefile.common clean && \
	cd .. && \
	cd brcm && \
	make -f Makefile.brcm clean && \
	cp ../Makefile.brcm . && \
	cd .. && \
	cd drm && \
	make -f Makefile.drm clean && \
	cp ../Makefile.drm . && \
	cd ..

cleanall: initall

initall: init
	rm -rf common && \
	rm -rf brcm && \
	rm -rf drm
   
init:
	rm -f .common && \
	rm -f .brcm && \
	rm -f .drm

parse-coverage:
	g++ parse-coverage.cpp -O2 -o parse-coverage

test-common: .common
	cd common && \
	make -f Makefile.common && \
	cd ..

.common:
	mkdir -p common && \
	cd common && \
	cp ../Makefile.common . && \
	make -f Makefile.common && \
	cd .. && \
	touch .common

test-brcm: .brcm
	cd brcm && \
	unset CFLAGS && \
	make -f Makefile.brcm && \
	cd ..

.brcm:
	git clone https://code.rdkcentral.com/r/a/components/opensource/westeros brcm && \
	cd brcm && \
	cp ../Makefile.brcm . && \
	cd .. && \
	touch .brcm

test-drm: .drm
	cd drm && \
	unset CFLAGS && \
	make -f Makefile.drm && \
	cd ..

.drm:
	git clone https://code.rdkcentral.com/r/a/components/opensource/westeros drm && \
	cd drm && \
	cp ../Makefile.drm . && \
	cd .. && \
	touch .drm

