#!/bin/sh

 if test -z "$XDG_RUNTIME_DIR"; then
    export XDG_RUNTIME_DIR=/run/user/`id -u`
 if ! test -d "$XDG_RUNTIME_DIR"; then
     mkdir -p $XDG_RUNTIME_DIR
     chmod 0700 $XDG_RUNTIME_DIR
     export XDG_RUNTIME_DIR=/run/user/`id -u`
    fi
 fi

#Dispmanx renderer support in RPI

 if [ -f /usr/lib/libwesteros_render_dispmanx.so.0 ]; then
   RENDERER=/usr/lib/libwesteros_render_dispmanx.so.0 --enableCursor
 else
   RENDERER=/usr/lib/libwesteros_render_gl.so.0
 fi

if [ -f "/run/user/`id -u`/wayland-0" ]; then
        echo "ERROR: A Wayland compositor is already running"
        exit 1
fi

